ddp:
    master_addr: "localhost"
    master_port: "0"
    num_devices: 1

rlbench:
    task_name: "multi"
    # tasks: [open_drawer,slide_block_to_color_target]
    tasks: [coordinated_push_box]
    demos: 1 # 100
    # demo_path: /my/demo/path
    demo_path: /home/zjyang/download/peract/squashfs-root-train
    episode_length: 2 # 25
    cameras: ["over_shoulder_left", "over_shoulder_right", "overhead", "wrist_right", "wrist_left", "front"]
    # camera_resolution: [128, 128]
    camera_resolution: [256,256]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
    include_lang_goal_in_obs: True

replay:
    batch_size: 4 # 8
    timesteps: 1
    prioritisation: False
    task_uniform: True # uniform sampling of tasks for multi-task buffers
    use_disk: True
    path: '/home/zjyang/program/peract_bimanual/log/arm/replay' 
    # path: '/tmp/arm/replay' # only used when use_disk is True.
    max_parallel_processes: 32

framework:
    log_freq: 100
    save_freq: 100 # 10000
    train_envs: 1
    replay_ratio: ${replay.batch_size}
    transitions_before_train: 200
    tensorboard_logging: True
    csv_logging: True
    training_iterations: 100 # 100000
    gpu: 0
    env_gpu: 0
    logdir: '/home/zjyang/program/peract_bimanual/log/arm_test' # '/tmp/arm_test/'
    # logdir: '/tmp/arm_test/'
    logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
    seeds: 1
    start_seed: 0
    load_existing_weights: False
    num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
    num_workers: 0
    record_every_n: 5
    checkpoint_name_prefix: "checkpoint"
    use_wandb: True
    wandb_project: "peract_bimanual"
    wandb_group: ${rlbench.task_name}_${method.name}
    seed: '0'  # 0
    wandb_name: ${framework.seed}

defaults:
    - method: PERACT_BC

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}
